input                  :  "/home/FCAM/etrybulec/nextflow_dev/samplesheet_test.csv"
outdir                 :  "test_outdir_2"
fastq                  :  "/core/projects/EBP/conservation/zigzag_coral/191/long_read/01_raw_reads/Mo_191_p1s.fastq"
centrifuge_db          :  "/core/labs/Wegrzyn/IngaGenome/Contam/longReads/f+b+a+v/"
busco_lineage          :  "metazoa_odb10"
summary_txt            :  "/archive/projects/EBP/roneill/reads/nanopore/promethion/DOG/Madrepora/Mo_S0424_FK21-191/2023JAN17_DOG_Mo_S0424_FK21-191_PAM25097/2023JAN17_DOG_Mo_S0424_FK21-191_PAM25097/20230117_2211_1C_PAM25097_ab58fe1c/sequencing_summary_PAM25097_ab58fe1c_a47ef4ef.txt"
mode                   :  "--nano-raw"
kraken_db              :  "/archive/labs/wegrzyn/transcriptomes/Juniper_Pine/Kraken/kraken_db"